rotiseria/Estadisticas/urls.py
from django.urls import path
from . import views

app_name = "Estadisticas"
urlpatterns = [
    path('', views.Estadisticas, name="Estadisticas"),
    path('listarVentas', views.ListarVentas, name="ListarVentas"),
    path('listarMenus', views.ListarMenus, name="ListarMenus"),
    path('listarCantidadesEntregadasPorCadete', views.ListarCantidadesEntregadasPorCadete, name="ListarCantidadesEntregadasPorCadete"),
    path('listarPlatosSolicitados', views.ListarPlatosSolicitados, name="ListarPlatosSolicitados"),

]

rotiseria/Menu/urls.py
from django.urls import path

from Carrito.views import restar_plato, agregar_plato, limpiar_carrito, eliminar_plato
from . import views

app_name = "Menu"
urlpatterns = [
    path('Normal', views.MenuNormal, name="menuNormal"),
    path('Vegetariano', views.MenuVegetariano, name="menuVegetariano"),
    path('Diabetico', views.MenuDiabetico, name="menuDiabetico"),
    path('Celiaco', views.MenuCeliaco, name="menuCeliaco"),
    path('Editar', views.EditarMenu, name="editarMenu"),
    path('EliminarPlato/<int:plato_id>/<int:menu_id>', views.QuitarPlato, name="quitarPlato"),
    path('AgregarPlato/<int:menu_id>', views.AgregarPlato, name="agregarPlato"),
    path('CambiarPrecioPlato/<int:plato_id>/<int:menu_id>', views.CambiarPrecioPlato, name="cambiarPrecioPlato"),
    path('agregar/<int:plato_id>/<int:menu_id>', agregar_plato, name="Add"),
    path('eliminar/<int:plato_id>/<int:menu_id>', eliminar_plato, name="Del"),
    path('restar/<int:plato_id>/<int:menu_id>', restar_plato, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

rotiseria/rotiseria/urls.py
from django.contrib import admin
from django.urls import path, include

from Cliente.views import index

urlpatterns = [
    path('Administrador/', include('Administrador.urls')),
    path('Cadete/', include('Cadete.urls')),
    path('Cliente/', include('Cliente.urls')),
    path('', index, name="index"),
    path('Estadisticas/', include('Estadisticas.urls')),
    path('Menu/', include('Menu.urls')),
    path('Pedido/', include('Pedido.urls')),
    path('Plato/', include('Plato.urls')),
    path('Usuario/', include('Usuario.urls')),
    path('Vianda/', include('Vianda.urls')),
    path('admin/', admin.site.urls),
]

rotiseria/Estadisticas/forms.py
from django import forms
from django.forms import SelectDateWidget

from Cadete.models import Cadete


class DateInput(forms.DateInput):
    input_type = 'date'


class DateRangeForm(forms.Form):
    Fecha_desde = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    Fecha_hasta = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, *args, **kwargs):
        super(DateRangeForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['type'] = 'date'


class DateRangeCadeteForm(forms.Form):
    Fecha_desde = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    Fecha_hasta = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    Cadete = forms.ModelChoiceField(queryset=Cadete.objects.all())

    def __init__(self, *args, **kwargs):
        super(DateRangeCadeteForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['type'] = 'date'

rotiseria/Estadisticas/views.py
from operator import itemgetter

from django.shortcuts import render
from Cadete.models import Cadete
from Estadisticas.forms import DateRangeForm, DateRangeCadeteForm
from Pedido.models import Pedido
from Plato.models import Plato


# Create your views here.

def Estadisticas(request):  # Vista comun que se ejecuta al entrar a la pág
    rangoFechasPedidosDiarios = DateRangeForm()  # Forms inicializados por cada estadistica disponible
    rangoFechasCantidadesCadete = DateRangeCadeteForm()
    rangoFechasPlatos = DateRangeForm()
    rangoFechasMenus = DateRangeForm()

    context = {  # Contexto. En todas las vistas incluye obligatoriamente los forms (para inicializarlos)
        'formPedidos': rangoFechasPedidosDiarios,
        'formMenus': rangoFechasMenus,
        'formCadete': rangoFechasCantidadesCadete,
        'formPlatos': rangoFechasPlatos,
    }
    return render(request, 'Estadisticas/estadisticas.html', context)


def ListarVentas(request):  # Listado de ventas/pedidos diarios en un rango de fechas
    pedidos = None  # Inicializada la variable en la que se almacenaran todos los pedidos realizados en un rango de fechas
    if request.method == 'POST':  # Si el formulario correspondiente fue completado
        rangoFechasPedidosDiarios = DateRangeForm(request.POST, request.FILES)
        if rangoFechasPedidosDiarios.is_valid():
            fecha_desde = rangoFechasPedidosDiarios[
                'Fecha_desde'].value()  # Se obtienen las fechas ingresadas por el usuario para obtener el rango de fecha en el que se obtendran los pedidos
            fecha_hasta = rangoFechasPedidosDiarios['Fecha_hasta'].value()
            pedidos = Pedido.objects.filter(fechaPedido__range=[fecha_desde,
                                                                fecha_hasta])  # Se obtienen (de la BD) todos los pedidos cuya fecha en la que fueron encargados se encuentra en el rango de fechas establecido anteriormente
    else:
        rangoFechasPedidosDiarios = DateRangeForm()  # Si el formulario no fue completado, entonces es inicializado para que el usuario tenga la oportunidad de completarlo
    print(
        rangoFechasPedidosDiarios.errors.as_data())  # Mensaje de error en consola en caso de que ocurra algun problema el cual deba ser investigado

    rangoFechasPedidosDiarios = DateRangeForm()
    rangoFechasCantidadesCadete = DateRangeCadeteForm()
    rangoFechasPlatos = DateRangeForm()
    rangoFechasMenus = DateRangeForm()

    context = {
        'formPedidos': rangoFechasPedidosDiarios,
        'formMenus': rangoFechasMenus,
        'formCadete': rangoFechasCantidadesCadete,
        'formPlatos': rangoFechasPlatos,
        'pedidos': pedidos,
        # Se envia dentro del contexto la variable pedidos para visualizar su información en el archivo HTML correspondiente
    }
    return render(request, 'Estadisticas/estadisticas.html', context)


def ListarCantidadesEntregadasPorCadete(request):
    pedidoCadete = None
    if request.method == 'POST':
        rangoFechasCantidadesCadete = DateRangeCadeteForm(request.POST,
                                                          request.FILES)  # Esta vista utiliza un Form distinto al resto, ya que ademas de pedir dos fechas tambien necesita saber qué cadete elegio.
        if rangoFechasCantidadesCadete.is_valid():
            fecha_desde = rangoFechasCantidadesCadete['Fecha_desde'].value()
            fecha_hasta = rangoFechasCantidadesCadete['Fecha_hasta'].value()
            cadete = rangoFechasCantidadesCadete[
                'Cadete'].value()  # Este formulario pide como valor extra, a un cadete encargado de llevar los pedidos. Se obtiene la clave primaria (o CUIL en este caso)
            ObjetoCadete = Cadete.objects.get(
                pk=cadete)  # Obtenemos la información del cadete utilizando la clave primaria
            cantidadEntregaPorCadete = cantidadPedidosDeUnCadete(ObjetoCadete, fecha_desde,
                                                                 fecha_hasta)  # Llamada a la función
            # cantidadPedidosDeUnCadete que se encarga de enumerar cuantos pedidos ha llevado un cadete en el rango
            # de fechas establecido

            nombreCadete = ObjetoCadete.nombre + ObjetoCadete.apellido  # La información que va a ser mostrada en
            # HTML, va a guardarse en una tupla de 3 elementos
            cuilCadete = ObjetoCadete.cuil
            pedidoCadete = (cuilCadete, nombreCadete, cantidadEntregaPorCadete)
    else:
        rangoFechasCantidadesCadete = DateRangeCadeteForm()
    print(rangoFechasCantidadesCadete.errors.as_data())
    rangoFechasPedidosDiarios = DateRangeForm
    rangoFechasPlatos = DateRangeForm()
    rangoFechasMenus = DateRangeForm()
    context = {
        'formPedidos': rangoFechasPedidosDiarios,
        'formMenus': rangoFechasMenus,
        'formCadete': rangoFechasCantidadesCadete,
        'formPlatos': rangoFechasPlatos,
        'pedidoCadete': pedidoCadete,
        # Envia la tupla con la información del cadete y la cantidad de pedidos entregados por este
    }
    return render(request, 'Estadisticas/estadisticas.html', context)


def cantidadPedidosDeUnCadete(cadete, fecha_desde,
                              fecha_hasta):  # Función utilizada por la vista ListarCantidadesEntregadasPorCadete. Se
    # encarga de contar cuantos pedidos fueron entregados por un cadete especifico en un rango de fechas establecido
    pedidos = Pedido.objects.filter(fechaPedido__range=[fecha_desde, fecha_hasta])
    contador = 0
    for pedido in pedidos:
        if (pedido.Cadete == cadete):
            contador += 1
    return contador


def ListarPlatosSolicitados(request):
    platosSolicitados = []
    if request.method == 'POST':
        rangoFechasMenus = DateRangeForm(request.POST, request.FILES)
        if rangoFechasMenus.is_valid():
            fecha_desde = rangoFechasMenus['Fecha_desde'].value()
            fecha_hasta = rangoFechasMenus['Fecha_hasta'].value()

            platos = Plato.objects.all()
            for plato in platos:  # Primero se almacena una lista de todos los platos registrados y por cada uno de
                # estos, obtenemos la información respecto a cuantas veces fue solicitado. Toda la información
                # relevante del plato es almacenada en una tupla la cual sera agregada a una lista de platos
                # solicitados.
                cantidadSolicitada = cantidadSolicitadaPlato(plato, fecha_desde, fecha_hasta)
                tuplaPlato = (plato.id, plato.nombre, plato.TipoPlato.tipoPlato, plato.Precio.precio, plato.Menu.tipo,
                              cantidadSolicitada)
                platosSolicitados.append(tuplaPlato)
            platosSolicitados = sorted(platosSolicitados, key=itemgetter(5),
                                       reverse=True)  # La lista es ordenada (de forma descencidente - reverse=True)
            # segun el 6to elemento (indice 5) de la tupla, el cual es la cantidad de veces que un plato fue
            # solicitado (key=itemgetter(5)
            platosSolicitados = platosSolicitados[
                                :5]  # Unicamente almacenamos los primeros 5 elementos de la lista (del indice 0 al
            # 5, sin incluir este ultimo)
    else:
        rangoFechasMenus = DateRangeForm()
    print(rangoFechasMenus.errors.as_data())

    rangoFechasPedidosDiarios = DateRangeForm()
    rangoFechasCantidadesCadete = DateRangeCadeteForm()
    rangoFechasPlatos = DateRangeForm()
    context = {
        'formPedidos': rangoFechasPedidosDiarios,
        'formMenus': rangoFechasMenus,
        'formCadete': rangoFechasCantidadesCadete,
        'formPlatos': rangoFechasPlatos,
        'platosSolicitados': platosSolicitados,
    }
    return render(request, 'Estadisticas/estadisticas.html', context)


def cantidadSolicitadaPlato(plato, fecha_desde,
                            fecha_hasta):  # Función utilizada por la vista ListarPlatosSolicitados. Se encarga de
    # contar cuantas veces un plato aparece en todos los pedidos realizados en un rango de fechas establecido.
    pedidos = Pedido.objects.filter(fechaPedido__range=[fecha_desde, fecha_hasta])
    contador = 0
    for pedido in pedidos:
        platosDelPedido = pedido.platos.all()
        for platoDelPedido in platosDelPedido:
            if plato.id == platoDelPedido.id:
                contador += 1
    return contador


def ListarMenus(request):  # Lista los menus e indica cuantas veces fueron solicitados
    menus = None
    if request.method == 'POST':
        rangoFechasMenus = DateRangeForm(request.POST, request.FILES)
        if rangoFechasMenus.is_valid():
            fecha_desde = rangoFechasMenus['Fecha_desde'].value()
            fecha_hasta = rangoFechasMenus['Fecha_hasta'].value()

            # Obtiene los valores de cuantos platos pedidos pertenecen a cada menu.
            cantidadNormal = cantidadPedidosDeUnMenu("Normal", fecha_desde, fecha_hasta)
            cantidadVegetariano = cantidadPedidosDeUnMenu("Vegetariano", fecha_desde, fecha_hasta)
            cantidadCeliaco = cantidadPedidosDeUnMenu("Celiaco", fecha_desde, fecha_hasta)
            cantidadDiabetico = cantidadPedidosDeUnMenu("Diabetico", fecha_desde, fecha_hasta)

            # Lista de tuplas, almacena el nombre de menu y la cantidad de veces que fue solicitado en algun plato.
            menus = [("Normal", cantidadNormal), ("Vegetariano", cantidadVegetariano), ("Celiaco", cantidadCeliaco),
                     ("Diabetico", cantidadDiabetico)]

            menus = sorted(menus, key=itemgetter(1),
                           reverse=True)  # Ordenado de mayor a menor, segun la cantidad de veces que fue solicitado.
    else:
        rangoFechasMenus = DateRangeForm()
    print(rangoFechasMenus.errors.as_data())
    rangoFechasPedidosDiarios = DateRangeForm()
    rangoFechasCantidadesCadete = DateRangeCadeteForm()
    rangoFechasPlatos = DateRangeForm()
    context = {

rotiseria/Estadisticas/templates/Estadisticas/estadisticas.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
    Estadísticas
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/estiloGeneral.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/estadisticas.css' %}" type="text/css" media="all">
{% endblock %}



{% block contenido %}
      <div class="container-fluid fondo" style="background-image: url({% static 'img/form-difuminado.png' %});">
        <br><br>
      <div id="listadoVentas">
        <h2>
          <span class="textoForm">Listado de ventas diarias</span>
        </h2>
        <form method="POST" name="listarVentasDiarias" action="{% url 'Estadisticas:ListarVentas' %}">
            {% csrf_token %}
          <div class="row">
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formPedidos.Fecha_desde.label}}</label>
                        {{formPedidos.Fecha_desde}}
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formPedidos.Fecha_hasta.label}}</label>
                        {{formPedidos.Fecha_hasta}}
                    </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
          </div>
      </form>
          {% if pedidos is None %}
            {% else %}
            <div class="text-center col-12 my-3">
            <table class="table-primary table-bordered border-light table-hover textoForm bg-dark">
                <thead>
                    <tr>
                        <th scope="col">Codigo</th>
                        <th scope="col">Persona</th>
                        <th scope="col">Fecha</th>
                        <th scope="col">Horario de entrega</th>
                        <th scope="col">Tipo de entrega</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Platos</th>
                        <th scope="col">Cadete a cargo</th>
                    </tr>
                </thead>

                <tbody>
                    {% for pedido in pedidos %}
                    <tr>
                        <th scope="row">{{pedido.id}}</th>
                        <td>{{pedido.Persona.nombre}} {{pedido.Persona.apellido}}</td>
                        <td>{{pedido.fechaPedido}}</td>
                        <td>{{pedido.horaEntregaDesde}} - {{pedido.horaEntregaHasta}}</td>
                        <td>{{pedido.TipoEntrega.tipoEntrega}}</td>
                        <td>{{pedido.Estado.estadoPedido}}</td>
                        <td>
                            <ul>
                            {% for plato in pedido.platos.all %}
                                <li>
                                    {{plato.nombre}}
                                </li>
                            {% endfor %}
                            </ul>
                        </td>
                        <td>{{pedido.Cadete.nombre}} {{pedido.Cadete.apellido}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          </div>
          {% endif %}



      </div>
        <br>
        <hr class="featurette-divider">
      <div id="listadoCantidadesPorCadete">
        <h2>
          <span class="textoForm">Listado de cantidades entregadas por el cadete</span>
        </h2>
        <form method="POST" name="listarCantidadEntregadaPorCadete" action="{% url 'Estadisticas:ListarCantidadesEntregadasPorCadete' %}">
            {% csrf_token %}
          <div class="row">
                    <div class="col-2">
                        <label class="form-label textoForm" class="textoForm">{{formCadete.Cadete.label}}</label>
                        {{formCadete.Cadete}}
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formCadete.Fecha_desde.label}}</label>
                        {{formCadete.Fecha_desde}}
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formCadete.Fecha_hasta.label}}</label>
                        {{formCadete.Fecha_hasta}}
                    </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
          </div>
      </form>
          {% if pedidoCadete is None %}
            {% else %}
            <div class="text-center col-12 my-3">
            <table class="table-primary table-bordered border-light table-hover textoForm bg-dark">
                <thead>
                    <tr>
                        <th scope="col">CUIL</th>
                        <th scope="col">Cadete</th>
                        <th scope="col">Cantidades entregadas</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <th scope="row">{{pedidoCadete.0}}</th>
                        <td>{{pedidoCadete.1}}</td>
                        <td>{{pedidoCadete.2}}</td>
                    </tr>
                </tbody>
            </table>
          </div>
          {% endif %}
        
      </div>
        <br>
        <hr class="featurette-divider">
         <!--
      <div id="listadoViandas">
        <h2>
          <span class="textoForm">Cantidad de viandas</span>
        </h2>
        <form method="GET" name="listarViandas">
            {% csrf_token %}
          <div class="row">
            <div class="col-3">
                        <label class="form-label textoForm" for="fechaDesde3" class="textoForm">Fecha desde</label>
                        <input class="form-control" class="fechaDesde" id="fechaDesde3" name="fechaDesde" type="date" required/>
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" for="fechaHasta3" class="textoForm">Fecha hasta</label>
                        <input class="form-control" class="fechaHasta" id="fechaHasta3" name="fechaDesde" type="date" required/>
                     </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
          </div>
      </form>

      </div>
          <br>
        <hr class="featurette-divider">
      <div id="listadoViandasPorZona">
        <h2>
          <span class="textoForm">Cantidad de viandas entregadas por zona</span>
        </h2>
        <form method="get" name="listarViandasPorZona">
            {% csrf_token %}
            <div class="row">
                <div class="col-2">
                    <select class="form-select" name="listaZona" id="listaZona">
                    {% for zona in zonas %}
                    <option value={{zona.id}}>{{zona.zona}}</option>
                    {% endfor %}
                </select>
                </div>

                <div class="col-8 row">
                    <div class="col-3">
                        <label class="form-label textoForm" for="fechaDesde4" class="textoForm">Fecha desde</label>
                        <input class="form-control" class="fechaDesde" id="fechaDesde4" name="fechaDesde" type="date" required/>
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" for="fechaHasta4" class="textoForm">Fecha hasta</label>
                        <input class="form-control" class="fechaHasta" id="fechaHasta4" name="fechaDesde" type="date" required/>
                     </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
                </div>
            </div>


          </form>

      </div>
          <br>
        <hr class="featurette-divider">
        -->
      <div id="listadoPlatos">
        <h2>
          <span class="textoForm">Listado de platos más solicitados</span>
        </h2>
        <form method="POST" name="listarPlatos" action="{% url 'Estadisticas:ListarPlatosSolicitados' %}">
            {% csrf_token %}
          <div class="row">
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formPlatos.Fecha_desde.label}}</label>
                        {{formPlatos.Fecha_desde}}
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formPlatos.Fecha_hasta.label}}</label>
                        {{formPlatos.Fecha_hasta}}
                    </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
          </div>
      </form>
          {% if platosSolicitados is None %}
            {% else %}
            <div class="text-center col-12 my-3">
            <table class="table-primary table-bordered border-light table-hover textoForm bg-dark">
                <thead>
                    <tr>
                        <!--
                         (plato.id,plato.nombre, plato.TipoPlato.tipoPlato, plato.Precio.precio, plato.Menu.tipo, cantidadSolicitadaPlato(plato, fecha_desde, fecha_hasta))
                         -->
                        <th scope="col">Codigo</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Tipo de plato</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Menu</th>
                        <th scope="col">Cantidad solicitada</th>
                    </tr>
                </thead>

                <tbody>
                    {% for plato in platosSolicitados %}
                    <tr>
                        <th scope="row">{{plato.0}}</th>
                        <td>{{plato.1}}</td>
                        <td>{{plato.2}}</td>
                        <td>${{plato.3}}</td>
                        <td>{{plato.4}}</td>
                        <td>{{plato.5}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          </div>
          {% endif %}

      </div>
          <br>
        <hr class="featurette-divider">
      <div id="listadoMenu">
        <h2>
          <span class="textoForm">Listado de menús más solicitados</span>
        </h2>

        <form method="POST" name="listarMenus" action="{% url 'Estadisticas:ListarMenus' %}">
            {% csrf_token %}
          <div class="row">
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formMenus.Fecha_desde.label}}</label>
                        {{formMenus.Fecha_desde}}
                    </div>
                    <div class="col-3">
                        <label class="form-label textoForm" class="textoForm">{{formMenus.Fecha_hasta.label}}</label>
                        {{formMenus.Fecha_hasta}}
                    </div>
                    <div class="col-4">
                        <input type="submit" class="btn btn-primary" value="Visualizar">
                    </div>
          </div>
      </form>
          {% if menus is None %}
            {% else %}
            <div class="text-center col-12 my-3">
            <table class="table-primary table-bordered border-light table-hover textoForm bg-dark">
                <thead>
                    <tr>
                        <th scope="col">Menu</th>
                        <th scope="col">Cantidad</th>
                    </tr>
                </thead>

                <tbody>
                    {% for menu in menus %}
                    <tr>
                        <th scope="row">{{menu.0}}</th>
                        <td>{{menu.1}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
          </div>
          {% endif %}

      </div>

    <br><br><br>
    </div>

{% endblock %}