rotiseria/Menu/urls.py
from django.urls import path

from Carrito.views import restar_plato, agregar_plato, limpiar_carrito, eliminar_plato
from . import views

app_name = "Menu"
urlpatterns = [
    path('Normal', views.MenuNormal, name="menuNormal"),
    path('Vegetariano', views.MenuVegetariano, name="menuVegetariano"),
    path('Diabetico', views.MenuDiabetico, name="menuDiabetico"),
    path('Celiaco', views.MenuCeliaco, name="menuCeliaco"),
    path('Editar', views.EditarMenu, name="editarMenu"),
    path('EliminarPlato/<int:plato_id>/<int:menu_id>', views.QuitarPlato, name="quitarPlato"),
    path('AgregarPlato/<int:menu_id>', views.AgregarPlato, name="agregarPlato"),
    path('CambiarPrecioPlato/<int:plato_id>/<int:menu_id>', views.CambiarPrecioPlato, name="cambiarPrecioPlato"),
    path('agregar/<int:plato_id>/<int:menu_id>', agregar_plato, name="Add"),
    path('eliminar/<int:plato_id>/<int:menu_id>', eliminar_plato, name="Del"),
    path('restar/<int:plato_id>/<int:menu_id>', restar_plato, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

rotiseria/rotiseria/urls.py
from django.contrib import admin
from django.urls import path, include

from Cliente.views import index

urlpatterns = [
    path('Administrador/', include('Administrador.urls')),
    path('Cadete/', include('Cadete.urls')),
    path('Cliente/', include('Cliente.urls')),
    path('', index, name="index"),
    path('Estadisticas/', include('Estadisticas.urls')),
    path('Menu/', include('Menu.urls')),
    path('Pedido/', include('Pedido.urls')),
    path('Plato/', include('Plato.urls')),
    path('Usuario/', include('Usuario.urls')),
    path('Vianda/', include('Vianda.urls')),
    path('admin/', admin.site.urls),
]

rotiseria/Menu/models.py
from django.db import models
from model_utils import Choices


# Create your models here.

class Menu(models.Model):
    NORMAL = "Normal"
    CELIACO = "Celiaco"
    VEGETARIANO = "Vegetariano"
    DIABETICO = "Diabetico"
    TIPO_MENU = (
        (NORMAL, "Normal"),
        (CELIACO, "Celiaco"),
        (VEGETARIANO, "Vegetariano"),
        (DIABETICO, "Diabetico")
    )

    tipo = models.CharField(max_length=15, choices=TIPO_MENU, default=NORMAL, unique=True)

    def __str__(self):
        return self.tipo

rotiseria/Menu/views.py
from datetime import date

from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

from Plato.models import Plato, Precio
from Menu.models import Menu

# Create your views here.
"""
def Menu(request):
    return render(request, 'Menu/menu.html')
"""


def MenuNormal(request):
    platos = Plato.objects.filter(Menu__tipo="Normal").filter(activo=True)

    entradas = platos.filter(TipoPlato__tipoPlato='Entrada')
    platosPrincipales = platos.filter(TipoPlato__tipoPlato='Plato principal')
    postres = platos.filter(TipoPlato__tipoPlato='Postre')
    NOMBRE_MENU = 'Menu normal'
    alerta = ('Para añadir platos a tu carrito, necesitas ingresar a tu cuenta.')
    context = {
        'NOMBRE_MENU': NOMBRE_MENU,
        'entradas': entradas,
        'platosPrincipales': platosPrincipales,
        'postres': postres,
        'menu_id': 1,
        'value.plato_id': 0,
        'alerta': alerta
    }

    return render(request, 'Menu/Menu.html', context)


def MenuVegetariano(request):
    platos = Plato.objects.filter(Menu__tipo="Vegetariano").filter(activo=True)
    entradas = platos.filter(TipoPlato__tipoPlato='Entrada')
    platosPrincipales = platos.filter(TipoPlato__tipoPlato='Plato principal')
    postres = platos.filter(TipoPlato__tipoPlato='Postre')
    NOMBRE_MENU = 'Menu vegetariano'
    alerta = ('Para añadir platos a tu carrito, necesitas ingresar a tu cuenta.')
    context = {
        'NOMBRE_MENU': NOMBRE_MENU,
        'entradas': entradas,
        'platosPrincipales': platosPrincipales,
        'postres': postres,
        'menu_id': 2,
        'value.plato_id': 0,
        'alerta': alerta
    }
    return render(request, 'Menu/Menu.html', context)


def MenuDiabetico(request):
    platos = Plato.objects.filter(Menu__tipo="Diabetico").filter(activo=True)
    entradas = platos.filter(TipoPlato__tipoPlato='Entrada')
    platosPrincipales = platos.filter(TipoPlato__tipoPlato='Plato principal')
    postres = platos.filter(TipoPlato__tipoPlato='Postre')
    NOMBRE_MENU = 'Menu diabetico'
    alerta = ('Para añadir platos a tu carrito, necesitas ingresar a tu cuenta.')
    context = {
        'NOMBRE_MENU': NOMBRE_MENU,
        'entradas': entradas,
        'platosPrincipales': platosPrincipales,
        'postres': postres,
        'menu_id': 3,
        'value.plato_id': 0,
        'alerta': alerta
    }
    return render(request, 'Menu/Menu.html', context)


def MenuCeliaco(request):
    platos = Plato.objects.filter(Menu__tipo="Celiaco").filter(activo=True)
    entradas = platos.filter(TipoPlato__tipoPlato='Entrada')
    platosPrincipales = platos.filter(TipoPlato__tipoPlato='Plato principal')
    postres = platos.filter(TipoPlato__tipoPlato='Postre')
    NOMBRE_MENU = 'Menu Celiaco'
    alerta = ('Para añadir platos a tu carrito, necesitas ingresar a tu cuenta.')
    context = {
        'NOMBRE_MENU': NOMBRE_MENU,
        'entradas': entradas,
        'platosPrincipales': platosPrincipales,
        'postres': postres,
        'menu_id': 4,
        'value.plato_id': 0,
        'alerta': alerta
    }
    return render(request, 'Menu/Menu.html', context)


def EditarMenu(request):
    if request.user.is_authenticated and request.user.is_staff:
        platosEnMenu = None
        platosInactivos = None
        MOSTRAR_DETALLE = False
        TIPO_MENU = None
        if request.GET.get("tipoMenu"):
            MOSTRAR_DETALLE = True
            TIPO_MENU = request.GET.get("tipoMenu")
            platos = Plato.objects.filter(Menu__id=TIPO_MENU)
            platosInactivos = platos.filter(activo=False)
            platosEnMenu = platos.filter(activo=True)
        menus = Menu.objects.all()
        context = {
            'menus': menus,
            'platosEnMenu': platosEnMenu,
            'platosInactivos': platosInactivos,
            'MOSTRAR_DETALLE': MOSTRAR_DETALLE,
            'TIPO_MENU': TIPO_MENU
        }
        return render(request, 'Menu/editarMenu.html', context)
    else:
        return redirect(reverse('Cliente:Index'))


def QuitarPlato(request, plato_id, menu_id):
    context = {

    }
    if request.user.is_authenticated and request.user.is_staff:
        plato = Plato.objects.get(pk=plato_id)
        plato.activo = False
        plato.save()

        MOSTRAR_DETALLE = True
        TIPO_MENU = menu_id
        platos = Plato.objects.filter(Menu__id=TIPO_MENU)
        platosInactivos = platos.filter(activo=False)
        platosEnMenu = platos.filter(activo=True)
        menus = Menu.objects.all()
        nombreMenu = Menu.objects.get(pk=TIPO_MENU).tipo
        context = {
            'menus': menus,
            'platosEnMenu': platosEnMenu,
            'platosInactivos': platosInactivos,
            'MOSTRAR_DETALLE': MOSTRAR_DETALLE,
            'TIPO_MENU': TIPO_MENU
        }

        messages.success(request, 'Ha eliminado el plato {} del menu {}.'.format(plato.nombre, nombreMenu))
    return render(request, 'Menu/editarMenu.html', context)


def CambiarPrecioPlato(request, plato_id, menu_id):
    platosInactivos = None
    platosEnMenu = None
    MOSTRAR_DETALLE = False
    TIPO_MENU = menu_id
    if request.user.is_authenticated and request.user.is_staff:
        if request.POST.get("precioPlato"):
            precio_plato = request.POST.get("precioPlato")
            precio_nuevo = Precio()
            precio_nuevo.precio = precio_plato
            precio_nuevo.fechaActualizacionPrecio = date.today()
            plato = Plato.objects.get(pk=plato_id)
            precio_nuevo.Plato = plato
            precio_nuevo.save()

            plato.Precio = precio_nuevo
            plato.save()


            MOSTRAR_DETALLE = True

            platos = Plato.objects.filter(Menu__id=TIPO_MENU)
            platosInactivos = platos.filter(activo=False)
            platosEnMenu = platos.filter(activo=True)
    menus = Menu.objects.all()
    context = {
        'menus': menus,
        'platosEnMenu': platosEnMenu,
        'platosInactivos': platosInactivos,
        'MOSTRAR_DETALLE': MOSTRAR_DETALLE,
        'TIPO_MENU': TIPO_MENU
    }
    return render(request, 'Menu/editarMenu.html', context)

def AgregarPlato(request, menu_id):
    platosEnMenu = None
    platosInactivos = None
    MOSTRAR_DETALLE = False
    TIPO_MENU = menu_id
    if request.user.is_authenticated and request.user.is_staff:
        if request.GET.get("platoMenu"):
            MOSTRAR_DETALLE = True
            plato_id = request.GET.get("platoMenu")
            plato = Plato.objects.get(pk=plato_id)
            plato.activo = True
            plato.save()

            platos = Plato.objects.filter(Menu__id=menu_id)
            platosInactivos = platos.filter(activo=False)
            platosEnMenu = platos.filter(activo=True)

            nombreMenu = Menu.objects.get(pk=TIPO_MENU).tipo
    menus = Menu.objects.all()
    context = {
        'menus': menus,
        'platosEnMenu': platosEnMenu,
        'platosInactivos': platosInactivos,
        'MOSTRAR_DETALLE': MOSTRAR_DETALLE,
        'TIPO_MENU': TIPO_MENU
    }

    messages.success(request, 'Ha agregado el plato {} al menu {}.'.format(plato.nombre, nombreMenu))
    return render(request, 'Menu/editarMenu.html', context)

rotiseria/Menu/templates/Menu/editarMenu.html
{% extends 'base/base.html' %}

{% load static %}


{% block title %}
    Editar menús
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/estiloGeneral.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/registro.css' %}" type="text/css" media="all">
{% endblock %}

{% block contenido %}
    <div class="container-fluid fondo" style="background-image: url({% static 'img/form-difuminado.png' %});">
            <hr class="featurette-divider">
            <div class="px-5 form">
                <form id="elegirMenu" action="{% url 'Menu:editarMenu' %}" method="GET">
                    <article id="tipoMenu">
                        <div class="px-5 my-5 mb-0">
                            <div class="text-center">
                                <h2>
                                   <span class="textoForm">Tipo de menu</span>
                                </h2>
                            </div>
                            <div>
                                <div class="row">
                                    <div class="col-3">

                                    </div>
                                    <div class="col-3">
                                        <label class="form-label textoForm" for="tipoMenu" ><span class="textoSecundario">Menu</span></label>
                                        <select class="form-select" name="tipoMenu" id="tipoMenu">
                                        {% for menu in menus %}
                                            <option value={{menu.id}} {% if TIPO_MENU == menu.id %} selected="selected" {% endif %}>{{menu.tipo}}</option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-2">

                                    </div>
                                    <div class="col-3" id="botonMenu">
                                        <input type="submit" class="btn btn-primary"  value="Editar">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </form>
            </div>
            {% if MOSTRAR_DETALLE %}
                <div class="text-center px-5 mx-5 mt-5 pb-5 row">
                <div class="col-3"></div>
                <div class="col-6">
                    <table class="table-primary table-bordered border-light table-hover textoForm bg-dark">
                <thead>
                    <tr>
                        <th scope="col">Codigo</th>
                        <th scope="col">Plato</th>
                        <th scope="col">Tipo de plato</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Acción</th>
                    </tr>
                </thead>

                <tbody>
                    {% for plato in platosEnMenu %}
                    <tr>
                        <th scope="row">{{plato.id}}</th>
                        <td>{{plato.nombre}}</td>
                        <td>{{plato.TipoPlato.tipoPlato}}</td>
                        <form method="POST" action="{% url 'Menu:cambiarPrecioPlato' plato.id TIPO_MENU %}" class="form-horizontal">
                            {% csrf_token %}
                        <td>
                            <div class="text-center w-auto row form-group">
                                <div class="col-1"></div>
                                <div class="col-9 ">
                                    <input name="precioPlato" id="precioPlato" class="form-control input-sm" type="number" value="{{plato.Precio.precio}}" required>
                                </div>

                            </div>

                        </td>
                        <td>

                            <input type="submit" class="btn btn-primary"  value="Guardar">
                            </form>
                            <a href="{% url 'Menu:quitarPlato' plato.id TIPO_MENU %}">
                                <button type="button" class="btn btn-danger" value="Quitar">Quitar</button>
                            </a>

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
                </div>
            </div>


            {% if platosInactivos %}
                <div>
                <form id="agregarPlato" action="{% url 'Menu:agregarPlato' TIPO_MENU %}" method="GET">
                    <article id="tipoMenu">
                        <div class="container-fluid px-5 my-5 mb-0">
                            <div class="text-center">
                                <h2>
                                   <span class="textoForm">Agregar platos a menú</span>
                                </h2>
                            </div>
                            <div>
                                <div class="row">
                                    <div class="col-2">

                                    </div>
                                    <div class="col-3">
                                        <label class="form-label textoForm" for="platoMenu" ><span class="textoSecundario">Plato</span></label>
                                        <input type="text" list="platosDisponibles" placeholder="Nombre del plato" class="form-control" name="platoMenu">
                                        <datalist id="platosDisponibles">
                                            {% for plato in platosInactivos %}
                                                <option value="{{plato.id}}">{{plato.nombre}}</option>
                                            {% endfor %}
                                        </datalist>
                                    </div>
                                    <div class="col-2">

                                    </div>
                                    <div class="col-3" id="botonMenu">
                                        <input type="submit" class="btn btn-primary"  value="Agregar">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </article>
                </form>
            </div>
            <br><br><br>
            {% endif %}

            {% else %}
            <br><br><br><br><br><br><br><br><br>
            {% endif %}
    </div>
{% endblock %}