rotiseria/Cadete/urls.py
from django.urls import path
from . import views

app_name = "Cadete"
urlpatterns = [
    path('', views.Cadete, name="registroCadete"),
]

rotiseria/Cliente/urls.py
from django.urls import path
from . import views

app_name = "Cliente"
urlpatterns = [
    #path('', views.Index, name="Index"),
    path('sobreNosotros/', views.SobreNosotros, name="SobreNosotros"),
    path('registroCliente/', views.RegistroCliente, name="RegistroCliente"),
]

rotiseria/Menu/urls.py
from django.urls import path

from Carrito.views import restar_plato, agregar_plato, limpiar_carrito, eliminar_plato
from . import views

app_name = "Menu"
urlpatterns = [
    path('Normal', views.MenuNormal, name="menuNormal"),
    path('Vegetariano', views.MenuVegetariano, name="menuVegetariano"),
    path('Diabetico', views.MenuDiabetico, name="menuDiabetico"),
    path('Celiaco', views.MenuCeliaco, name="menuCeliaco"),
    path('Editar', views.EditarMenu, name="editarMenu"),
    path('EliminarPlato/<int:plato_id>/<int:menu_id>', views.QuitarPlato, name="quitarPlato"),
    path('AgregarPlato/<int:menu_id>', views.AgregarPlato, name="agregarPlato"),
    path('CambiarPrecioPlato/<int:plato_id>/<int:menu_id>', views.CambiarPrecioPlato, name="cambiarPrecioPlato"),
    path('agregar/<int:plato_id>/<int:menu_id>', agregar_plato, name="Add"),
    path('eliminar/<int:plato_id>/<int:menu_id>', eliminar_plato, name="Del"),
    path('restar/<int:plato_id>/<int:menu_id>', restar_plato, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

rotiseria/Pedido/urls.py
from django.urls import path
from . import views

app_name = "Pedido"
urlpatterns = [
    path('', views.Pedido, name="registroPedido"),
    path('pedidoCliente', views.PedidoCliente, name="pedidoCliente")
]

rotiseria/Plato/urls.py
from django.urls import path
from . import views

app_name = "Plato"
urlpatterns = [
    path('', views.Plato, name="registrar"),
]

rotiseria/rotiseria/urls.py
from django.contrib import admin
from django.urls import path, include

from Cliente.views import index

urlpatterns = [
    path('Administrador/', include('Administrador.urls')),
    path('Cadete/', include('Cadete.urls')),
    path('Cliente/', include('Cliente.urls')),
    path('', index, name="index"),
    path('Estadisticas/', include('Estadisticas.urls')),
    path('Menu/', include('Menu.urls')),
    path('Pedido/', include('Pedido.urls')),
    path('Plato/', include('Plato.urls')),
    path('Usuario/', include('Usuario.urls')),
    path('Vianda/', include('Vianda.urls')),
    path('admin/', admin.site.urls),
]

rotiseria/templates/base/base.html
{% load static %}
{% load custom-tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://getbootstrap.com/docs/5.0/examples/carousel/carousel.css">
  <!-- CSS personalizado -->
  <link rel="stylesheet" href="{% static 'css/barraNavegacion.css' %}" type="text/css">
  <!-- Bootstrap JS, , Jquery -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>  <!-- Lo que hace que funcione el carrousel, puede ser comentado-->
  <script src="https://kit.fontawesome.com/5703f194c3.js" crossorigin="anonymous"></script>  <!--Link para utilizar iconos de Font Awesome. Son temporales-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  {% block head %} {% endblock %}
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-lg">   <!-- Barra de navegacion, la clase "fixed-top" mantiene fija la barra sin importar donde este situado el usuario-->
          <div class="navbar-left">
            <img src="{% static 'img/logo-rotiseria-redimensionada.png' %}" alt="logo" class="logo">
          </div>
            {% block carrito%}
            {% endblock%}
          <div class="barraNavegacion mx-auto" style="visibility: hidden;">
            <form class="" id="barraBusqueda">
              <div class="input-group rounded">
                  <input type="search" class="form-control rounded" id="textoBarra" placeholder="Qué estas buscando?" aria-label="Search" aria-describedby="search-addon" /> <!-- Barra de busqueda -->
                  <button class="btn btn-primary" type="submit">
                      <span class="input-group-text" id="search-addon"> <!-- Imagen de busqueda (boton incorporado). Actualmente no funciona la imagen -->
                          <i class="fa fa-search"></i> <!-- Logo de Font Awesome -->
                        </span>
                  </button>

              </div>





            </form>
          </div>

          <div class="navbar-right">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span></button> <!-- Opcion que aparece en resoluciones menores, permite abrir lista deplegable con las opciones de Home, Sobre nosotros, etc.-->

            <div class="container-fluid  px-1 px-lg-1 ms-auto" id="opcionesBarraNavegacion">
              <!--<div class="navbar-left">
               <img src="Imagenes/logo-rotiseria.png" alt="logo" class="logo">-->
               <!--<a class="navbar-brand" href="#"><img src="Imagenes/logo-rotiseria.png" alt=""></a>--> <!-- Nombre/Logo de la marca-->


               <div class="collapse navbar-collapse" id="navbarSupportedContent">


                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4" >    <!-- Lista con las opciones de la barra de navegacion-->
                    <li class="nav-item"><a class="nav-link active" id="texto-color" aria-current="page" href="{% url 'index' %}">Home</a></li>
                    <li class="nav-item dropdown"> <!-- Lista deplegable de menús, solo funciona con bootstrap.bundle.min.js. Si queres activarla, debes sacar el comentario que rodea a la etiqueta link más arriba -->
                        <a class="nav-link dropdown-toggle" id="texto-color" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Menús</a>


                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a id="texto-color" class="dropdown-item" href="{% url 'Menu:menuNormal' %}">Normal</a></li>
                            <li><a  id="texto-color" class="dropdown-item" href="{% url 'Menu:menuCeliaco' %}">Apto para celíacos</a></li>
                            <li><a id="texto-color" class="dropdown-item" href="{% url 'Menu:menuDiabetico' %}">Recomendado para diabeticos</a></li>
                            <li><a id="texto-color" class="dropdown-item" href="{% url 'Menu:menuVegetariano' %}">Veggie</a></li>
                            {% if user.is_authenticated and user.is_superuser %}
                                <li><hr class="dropdown-divider" /></li> <!-- Esta opcion es para mostrar una linea divisoria entre las opciones de la lista deplegable, puede ser util en otra situacion -->
                                <li><a id="texto-color" class="dropdown-item" href="{% url 'Plato:registrar' %}">Registrar plato</a></li>
                                <li><a id="texto-color" class="dropdown-item" href="{% url 'Menu:editarMenu' %}">Editar menús</a></li>


                            {% endif %}
                        </ul>


                    </li>
                    {% if user.is_authenticated%}

                            <li class="nav-item dropdown"> <!-- Lista deplegable de menús, solo funciona con bootstrap.bundle.min.js. Si queres activarla, debes sacar el comentario que rodea a la etiqueta link más arriba -->
                            <a class="nav-link dropdown-toggle" id="texto-color" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Pedidos</a>


                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if user.is_superuser or user|has_group:"Cadete" %}
                                    {% if user.is_superuser %}
                                    <li><a id="texto-color" class="dropdown-item" href="{% url 'Pedido:registroPedido' %}">Registrar pedido</a></li>
                                    <li><a  id="texto-color" class="dropdown-item" href="{% url 'Administrador:estadoPedidos' %}">Estado de pedidos</a></li>
                                    <li><a id="texto-color" class="dropdown-item" href="{% url 'Estadisticas:Estadisticas' %}">Estadisticas</a></li>
                                    {% else %}
                                    <li><a id="texto-color" class="dropdown-item" href="{% url 'Administrador:estadoPedidosCadete' %}">Estado de pedidos</a></li>
                                    {% endif %}
                                {% else %}
                                    <li><a id="texto-color" class="dropdown-item" href="{% url 'Administrador:estadoPedidoCliente' %}">Mis pedidos</a></li>
                                {% endif %}
                        </ul>
                                {% endif %}
                    </li>


                    {% if user.is_authenticated and user.is_superuser %}
                        <li class="nav-item dropdown"> <!-- Lista deplegable de menús, solo funciona con bootstrap.bundle.min.js. Si queres activarla, debes sacar el comentario que rodea a la etiqueta link más arriba -->
                        <a class="nav-link dropdown-toggle" id="texto-color" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Administración</a>


                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a id="texto-color" class="dropdown-item" href="{% url 'Cliente:RegistroCliente' %}">Registrar cliente</a></li>
                            <li><a  id="texto-color" class="dropdown-item" href="{% url 'Cadete:registroCadete' %}">Registrar cadete</a></li>
                        </ul>
                    </li>
                    {% else %}
                        <li class="nav-item"><a id="texto-color" class="nav-link" href="{% url 'Cliente:SobreNosotros' %}">Sobre nosotros</a></li>
                    {% endif %}

                    <li class="nav-item">
                        <div class="input-group">
                             <!-- Logo de login <i class="fa fa-sign-in" aria-hidden="true"></i> -->
                            {% if user.is_authenticated %}
                                <a id="texto-color" class="nav-link" href ="{% url 'Usuario:logout' %}">Cerrar sesión</a>
                            {% else %}
                                <a id="texto-color" class="nav-link" href="{% url 'Usuario:login' %}">Ingresar</a>
                            {% endif %}
                        </div>
                    </li>
                  </ul>
              </div>
           </div>
          </div>

          </nav>
    </header>
    <section>
      {% block contenido %}
      {% endblock %}
    </section>

    <hr class="featurette-divider">
    <!-- /END THE FEATURETTES -->
    <!-- FOOTER -->
    <footer class="container-fluid"> <!-- Footer correspondiente -->
      <p class="float-end">
        <a id="footerText" href="#">
          Volver al inicio
        </a>
      </p>
      <p id="footerText">
        © 2022 Rotiseria El Mejor Sabor ©
        <br>
        <a id="footerText" href="#">
          Privacidad
        </a> ·
        <a id="footerText" href="#">
          Terminos y condiciones
        </a>
      </p>
    </footer>
    {% if messages %}
        {% for message in messages %}
            <script>
                alert("{{message}}");
            </script>
        {% endfor %}
    {% endif %}
    </body>
</html>