rotiseria/Administrador/urls.py
from django.urls import path
from . import views

app_name = "Administrador"
urlpatterns = [
    path('', views.pedido_lista, name="estadoPedidos"),
    path('Cadete', views.pedido_lista_cadete, name="estadoPedidosCadete"),
    path('Cliente', views.pedido_lista_cliente, name="estadoPedidoCliente"),
    path('cambiarEstadoPedidoConComentario/<int:pedido_id>', views.cambiarEstadoPedidoConComentario, name="cambiarEstadoPedidoConComentario"),

]

rotiseria/Menu/urls.py
from django.urls import path

from Carrito.views import restar_plato, agregar_plato, limpiar_carrito, eliminar_plato
from . import views

app_name = "Menu"
urlpatterns = [
    path('Normal', views.MenuNormal, name="menuNormal"),
    path('Vegetariano', views.MenuVegetariano, name="menuVegetariano"),
    path('Diabetico', views.MenuDiabetico, name="menuDiabetico"),
    path('Celiaco', views.MenuCeliaco, name="menuCeliaco"),
    path('Editar', views.EditarMenu, name="editarMenu"),
    path('EliminarPlato/<int:plato_id>/<int:menu_id>', views.QuitarPlato, name="quitarPlato"),
    path('AgregarPlato/<int:menu_id>', views.AgregarPlato, name="agregarPlato"),
    path('CambiarPrecioPlato/<int:plato_id>/<int:menu_id>', views.CambiarPrecioPlato, name="cambiarPrecioPlato"),
    path('agregar/<int:plato_id>/<int:menu_id>', agregar_plato, name="Add"),
    path('eliminar/<int:plato_id>/<int:menu_id>', eliminar_plato, name="Del"),
    path('restar/<int:plato_id>/<int:menu_id>', restar_plato, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

rotiseria/rotiseria/urls.py
from django.contrib import admin
from django.urls import path, include

from Cliente.views import index

urlpatterns = [
    path('Administrador/', include('Administrador.urls')),
    path('Cadete/', include('Cadete.urls')),
    path('Cliente/', include('Cliente.urls')),
    path('', index, name="index"),
    path('Estadisticas/', include('Estadisticas.urls')),
    path('Menu/', include('Menu.urls')),
    path('Pedido/', include('Pedido.urls')),
    path('Plato/', include('Plato.urls')),
    path('Usuario/', include('Usuario.urls')),
    path('Vianda/', include('Vianda.urls')),
    path('admin/', admin.site.urls),
]

rotiseria/Administrador/models.py
"""
from django.db import models
from Persona.models import Persona
from Persona.models import Direccion
from Persona.models import Zona
from Persona.models import Telefono

# Create your models here.

class Administrador(Persona):
    pass

"""

rotiseria/Administrador/forms.py
from django.forms import forms
from django import forms
from django.forms import ModelForm

from Cadete.models import Cadete


class DateInput(forms.DateInput):
    input_type = 'date'


class ActualizarPedidoForm(forms.Form):
    ESTADO_OPCIONES = (
        (1, "Pendiente"), (2, "En preparación"), (3, "En camino"), (4, "Entregado"), (5, "Devuelto"),
        (6, "Cancelado"))

    estadoPedido = forms.ChoiceField(choices=ESTADO_OPCIONES, label=False)
    comentario = forms.CharField(max_length=500, label=False)

rotiseria/Administrador/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse

from Administrador.forms import ActualizarPedidoForm
from Cadete.models import Cadete
from Pedido.models import Pedido, Estado

# Create your views here.
"""
def Administrador(request):
    return render(request,'Administrador/estadoPedidos.html')
"""


def pedido_lista(request):
    if request.user.is_authenticated and request.user.is_staff:
        pedidos = Pedido.objects.all()
        formEstado = ActualizarPedidoForm()
        context = {
            'pedidos': pedidos,
            'form': formEstado,
        }
        return render(request, 'Administrador/estadoPedidos.html', context)
    else:
        return redirect(reverse('Cliente:Index'))


def pedido_lista_cadete(request):
    if request.user.is_authenticated:
        cadete = Cadete.objects.get(usuario=request.user)

        pedidosCadete = Pedido.objects.filter(Cadete=cadete)
        formEstado = ActualizarPedidoForm()

        context = {
            'pedidos': pedidosCadete,
            'form': formEstado,
        }
        return render(request, 'Administrador/estadoPedidos.html', context)
    else:
        return redirect(reverse('Cliente:Index'))


def pedido_lista_cliente(request):
    if request.user.is_authenticated:
        cliente = request.user.Cliente

        pedidosCliente = Pedido.objects.filter(Persona=cliente)
        formEstado = ActualizarPedidoForm()

        context = {
            'pedidos': pedidosCliente,
            'form': formEstado,
        }
        return render(request, 'Administrador/estadoPedidos.html', context)
    else:
        return redirect(reverse('Cliente:Index'))


def cambiarEstadoPedidoConComentario(request, pedido_id):
    if request.method == 'POST':
        formEstado = ActualizarPedidoForm(request.POST, request.FILES)
        if formEstado.is_valid():
            estado_id = formEstado.cleaned_data['estadoPedido']
            comentario = formEstado.cleaned_data['comentario']

            pedido = Pedido.objects.filter(pk=pedido_id).first()
            estadoPedido = Estado.objects.filter(pk=estado_id).first()
            pedido.Estado = estadoPedido
            pedido.comentario = comentario

            pedido.save()
    if request.user.groups.filter(name='Cadete').exists():
        return redirect(reverse('Administrador:estadoPedidosCadete'))
    else:
        return redirect(reverse('Administrador:estadoPedidos'))

rotiseria/Administrador/templates/Administrador/estadoPedidos.html
{% extends 'base/base.html' %}

{% load static %}

{% block title %}
    Estado de pedidos
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/estadoPedidos.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" type="text/css" media="all">
    <link rel="stylesheet" href="{% static 'css/estiloGeneral.css' %}" type="text/css">

    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
{% endblock %}
{% block contenido %}
    <div>
        <div class="image-aboutus-banner fondo" style="margin-top:70px; background: linear-gradient(rgba(0,0,0,.7), rgba(0,0,0,.7)), url({% static 'img/frente-nosotros.jpg' %});">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="text-center">
                            <h1 class="lg-text titulos">
                                {% if user.is_staff %}
                                Listado de pedidos
                                {% else %}
                                Mis pedidos
                                {% endif %}
                            </h1>
                        </div>

                    <!-- <p class="image-aboutus-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>  -->
                    </div>
                </div>
            </div>
         </div>
         <hr class="featurette-divider">
         <div class="paddingTB60" style="background-image: url({% static 'img/form-difuminado.png' %});background-repeat: no-repeat;background-size: cover;background-position:center;overflow: hidden;">
             <div class="container" id="listaPedidos">
                 {% for pedido in pedidos %}
                    <ul class="list-group list-group-horizontal">
                    <a href="#" class="list-group-item list-group-item-action">
                        <div class="d-flex w-60 justify-content-between">
                          <h5 class="mb-1">{{pedido.Persona.nombre}} {{pedido.Persona.apellido}}</h5>
                          <small class="text-muted">{{pedido.fechaPedido}}</small>

                        </div>
                        <div class="d-flex w-60 justify-content-between">
                            <p class="mb-1">
                                {% if pedido.platos.all.count == 1 %}
                                    {% for plato in pedido.platos.all %}
                                        {{plato.nombre}}
                                    {% endfor %}
                                {% else %}
                                    {% for plato in pedido.platos.all %}
                                        {{plato.nombre}},
                                    {% endfor %}
                                {% endif %}
                            </p>
                            <small class="text-muted">Tiempo de entrega estimado</small>
                        </div>
                        <div class="d-flex w-60 justify-content-between">
                            <small class="text-muted">{{pedido.TipoEntrega.tipoEntrega}}</small>
                            <small class="text-muted">{{pedido.horaEntregaDesde}}- {{pedido.horaEntregaHasta}}</small>
                        </div>
                    </a>
                    <li class="list-group-item">
                        {% if user.is_staff %}
                        <form method="post" action="{% url 'Administrador:cambiarEstadoPedidoConComentario' pedido.id %}">
                            <div class="text-center">
                                {% csrf_token %}
                                <select name="estadoPedido" class="selectpicker form-select">
                                    {% for valor,texto in form.fields.estadoPedido.choices %}
                                        {% if valor == pedido.Estado.id %}
                                            <option value="{{valor}}" selected>{{texto}}</option>
                                        {% else %}
                                            <option value="{{valor}}">{{texto}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                                {% if pedido.comentario is None %}
                                    <input type="text" name="comentario" maxlength="500" required value="" id="id_comentario">
                                {% else %}
                                    <input type="text" name="comentario" maxlength="500" required value="{{pedido.comentario}}" id="id_comentario">
                                {% endif %}


                                <button type="submit" class="btn btn-primary pl-2" id="guardarEstadoPedido">Guardar</button>
                            </div>
                        </form>
                        {% else %}
                            <div class="text-center">
                                {% csrf_token %}
                                <select name="estadoPedido" class="selectpicker form-select" disabled>
                                    {% for valor,texto in form.fields.estadoPedido.choices %}
                                        {% if valor == pedido.Estado.id %}
                                            <option value="{{valor}}" selected>{{texto}}</option>
                                        {% else %}
                                            <option value="{{valor}}">{{texto}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                        {% endif %}


                        <!--<input class="mt-2 estadoEntrega" type="text" placeholder="Comentario"> -->


                    </li>
                </ul>
                 {% endfor %}
             </div>
         </div>
    </div>

    <script src="{% static 'js/estadoPedidos.js' %}" type="text/javascript"></script>
{% endblock %}-